"""asdfasfd

Revision ID: 5e6afc6ef343
Revises: 7d5a25a758b0
Create Date: 2024-08-05 00:54:40.634925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6afc6ef343'
down_revision = '7d5a25a758b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TESTER', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('TESTER')

    # ### end Alembic commands ###
