"""asdfasfd

Revision ID: 2cf5f0c6bb05
Revises: 5e6afc6ef343
Create Date: 2024-08-05 00:55:45.372726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf5f0c6bb05'
down_revision = '5e6afc6ef343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('TESTER')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TESTER', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
