"""drop test column

Revision ID: 88085d03f660
Revises: ff5e2a8198b5
Create Date: 2024-08-01 17:52:34.916417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88085d03f660'
down_revision = 'ff5e2a8198b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_testst_key', type_='unique')
        batch_op.drop_column('testst')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testst', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_testst_key', ['testst'])

    # ### end Alembic commands ###
