"""Test

Revision ID: ff5e2a8198b5
Revises: 057859b9bd3d
Create Date: 2024-08-01 17:47:47.402780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5e2a8198b5'
down_revision = '057859b9bd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testst', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint(None, ['testst'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('testst')

    # ### end Alembic commands ###
