"""Test Migration - Revert

Revision ID: cac78d14f7b9
Revises: c8643fea5a99
Create Date: 2024-08-05 01:03:59.920827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac78d14f7b9'
down_revision = 'c8643fea5a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('testerrr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testerrr', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
